CREATE TABLE IF NOT EXISTS Album (
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(250) NOT NULL,
    description VARCHAR(750) NOT NULL,
    cover_url VARCHAR(500),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Photo (
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(250) NOT NULL,
    description VARCHAR(750) NOT NULL,
    url VARCHAR(500) NOT NULL,
    album_id INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (album_id) REFERENCES Album(id) ON DELETE CASCADE
);

